title: My Awesome Site  
author: Typhaney Bennett
email: Typhaney@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Practicing with github

# social links
twitter_username: typhaneybdev
github_username:  typhaneybdev

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
